### PR TITLE
Update workflows

### PR DESCRIPTION
**Pull request by damacus**
# Description

Update GitHub workflows

## Issues Resolved

List any existing issues this PR resolves

## CheckList

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by xorima — APPROVED** [review]

**Comment by flame4** [comment]
Hey. @damacus after you commit this pr, our pipeline had a problem here, msg like:
```
Pull down action image 'ghcr.io/actionshub/yamllint:1.1.0'
  /usr/bin/docker pull ghcr.io/actionshub/yamllint:1.1.0
  Error response from daemon: manifest unknown
```

not sure whether your team should update something?

Thanks for your attention!

**Comment by xorima** [comment]
Let me take a look in a bit @flame4 
Thanks for reporting this

**Comment by xorima** [comment]
Hey @flame4 

I've run some tests and it appears to be working, https://github.com/sous-chefs/sc_vscode/actions/runs/3695246307/jobs/6257391173 can you check your side and see if it works for you?

**Comment by flame4** [comment]
> Hey @flame4
> 
> I've run some tests and it appears to be working, https://github.com/sous-chefs/sc_vscode/actions/runs/3695246307/jobs/6257391173 can you check your side and see if it works for you?

@Xorima Thanks for your time. After hours retrying, it works finally. So I think it must be some network issue on my zone, never mind!

**Comment by damacus** [comment]
No that was totally my fault. I forgot to add the v before the tag. Apologies for that!

**Pull request merged**
